name: check_bull_market_every_9AM

on:
  schedule:
    - cron: "0 */4 * * *" # 4시간마다 실행
    - cron: "0 0,12 * * *" # 12시간마다 실행 (UTC 0시, 12시)
  push:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || contains(github.event.schedule, '*/4')
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run main.py
        run: |
          python main.py
        env:
          UPBIT_ACCESS: ${{ secrets.UPBIT_ACCESS }}
          UPBIT_SECRET: ${{ secrets.UPBIT_SECRET }}
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GOOGLE_SHEETS_TYPE: ${{ secrets.GOOGLE_SHEETS_TYPE }}
          GOOGLE_SHEETS_PROJECT_ID: ${{ secrets.GOOGLE_SHEETS_PROJECT_ID }}
          GOOGLE_SHEETS_PRIVATE_KEY_ID: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY_ID }}
          GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
          GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
          GOOGLE_SHEETS_CLIENT_ID: ${{ secrets.GOOGLE_SHEETS_CLIENT_ID }}
          GOOGLE_SHEETS_AUTH_URI: ${{ secrets.GOOGLE_SHEETS_AUTH_URI }}
          GOOGLE_SHEETS_TOKEN_URI: ${{ secrets.GOOGLE_SHEETS_TOKEN_URI }}
          GOOGLE_SHEETS_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.GOOGLE_SHEETS_AUTH_PROVIDER_X509_CERT_URL }}
          GOOGLE_SHEETS_CLIENT_X509_CERT_URL: ${{ secrets.GOOGLE_SHEETS_CLIENT_X509_CERT_URL }}
          ALPHASQUARED_API_KEY: ${{ secrets.ALPHASQUARED_API_KEY }}

  # 12시간마다 실행될 작업
  asset-allocation-log:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || contains(github.event.schedule, '0,12')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run special task
        run: |
          python asset-allocation.py
        env:
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GOOGLE_SHEETS_TYPE: ${{ secrets.GOOGLE_SHEETS_TYPE }}
          GOOGLE_SHEETS_PROJECT_ID: ${{ secrets.GOOGLE_SHEETS_PROJECT_ID }}
          GOOGLE_SHEETS_PRIVATE_KEY_ID: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY_ID }}
          GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
          GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
          GOOGLE_SHEETS_CLIENT_ID: ${{ secrets.GOOGLE_SHEETS_CLIENT_ID }}
          GOOGLE_SHEETS_AUTH_URI: ${{ secrets.GOOGLE_SHEETS_AUTH_URI }}
          GOOGLE_SHEETS_TOKEN_URI: ${{ secrets.GOOGLE_SHEETS_TOKEN_URI }}
          GOOGLE_SHEETS_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.GOOGLE_SHEETS_AUTH_PROVIDER_X509_CERT_URL }}
          GOOGLE_SHEETS_CLIENT_X509_CERT_URL: ${{ secrets.GOOGLE_SHEETS_CLIENT_X509_CERT_URL }}
